build: false

environment:
    PYTHON_HOME: "C:\\Python37"
    CONAN_VISUAL_RUNTIMES: MD,MDd   # Ignoring MT and MTd
    CONAN_ARCHS: x86_64   # Don't want to build for x86

    matrix:

        # 2017 is the target MSVC for now, so build Release and Debug, x64 only
        #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        #  CONAN_VISUAL_VERSIONS: 15
        #  CONAN_BUILD_TYPES: Release,Debug

        # Teesting MSVC 2019, both Release and Debug, x64 only
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release,Debug

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
- python build.py
